version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "test_requirements.txt" }}

      - run:
          name: install
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r test_requirements.txt

      - run:
          name: run tests and generate coverage
          command: |
            . venv/bin/activate
            cd gilp
            coverage run -m pytest
            coverage xml

      - run:
          name: upload coverage to codecov
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: run linting via flake8
          command: |
            . venv/bin/activate
            flake8 gilp

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "test_requirements.txt" }}
          paths:
            - "venv"

      - store_artifacts:
          path: test-reports
          destination: test-reports